// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "creditsdebitscontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CreditsDebitsControl

IMPLEMENT_DYNCREATE(CreditsDebitsControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CreditsDebitsControl properties

/////////////////////////////////////////////////////////////////////////////
// CreditsDebitsControl operations

void CreditsDebitsControl::StartInitialize()
{
	InvokeHelper(0x6003000d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
