#if !defined(AFX_CREDITSDEBITSCONTROL_H__FFA4F0EC_3D73_4790_A054_3842EC7405CD__INCLUDED_)
#define AFX_CREDITSDEBITSCONTROL_H__FFA4F0EC_3D73_4790_A054_3842EC7405CD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CreditsDebitsControl wrapper class

class CreditsDebitsControl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CreditsDebitsControl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xbb643ebf, 0xa1f9, 0x4656, { 0xb6, 0x14, 0x3, 0xd4, 0xe6, 0x4, 0xa6, 0xc9 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void StartInitialize();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CREDITSDEBITSCONTROL_H__FFA4F0EC_3D73_4790_A054_3842EC7405CD__INCLUDED_)
